server:
  servlet:
    context-path: /AdminEmployeePortalSpringBoot
spring:
  datasource: 
    url: jdbc:mysql://localhost/employeePortalDatabase
    username: root
    password: pass123
    driver-class-name : com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
  mail:
    host: smtp.gmail.com
    port: 587
    username: metacubeid@gmail.com
    password: xqigpgsxddusjory
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true